feat(jwt): change the authentication token format from JWT to custom JSON + signature
web-eid/web-eid-app pull request #151
Opened 2021-10-15 17:01 UTC by mrts

Refs WE2-585

2021-11-12 19:43 UTC, mrts commented on src/controller/command-handlers/authenticate.cpp
> +    const auto nonceHash = QCryptographicHash::hash(nonce.toUtf8(), QCryptographicHash::Sha256);
Use `challenge` instead of `nonce` throughout.

2021-12-01 07:33 UTC, metsma requested changes

2021-12-01 07:33 UTC, metsma commented on src/controller/command-handlers/authenticate.cpp
> +const auto BASE64_OPTIONS = QByteArray::Base64Encoding | QByteArray::KeepTrailingEquals;
```suggestion
constexpr auto BASE64_OPTIONS = QByteArray::Base64Encoding | QByteArray::KeepTrailingEquals;
```

2021-12-01 07:33 UTC, metsma commented on src/controller/command-handlers/authenticate.cpp
> +    const auto originHash = QCryptographicHash::hash(origin.toUtf8(), QCryptographicHash::Sha256);
I think we should lead use same hash algo as used in signature

2021-12-03 10:12 UTC, metsma approved these changes

2021-12-03 12:44 UTC, merged