Use Qt 6.5 styleHint colorScheme to detect dark theme
web-eid/web-eid-app pull request #295
Opened 2023-10-12 08:47 UTC by metsma

- keep linux compatibility

WE2-826

Signed-off-by: Raul Metsma <raul@metsma.ee>

2024-02-23 20:04 UTC, mrts requested changes

2024-02-23 20:04 UTC, mrts commented on src/controller/application.cpp
> +        QProcess::startDetached(applicationFilePath());
This seems a bit unconventional - we launch a new copy of the application to show the _About_ dialog?

2024-02-23 20:04 UTC, mrts commented on src/controller/application.cpp
>  #else
I think we should make it explicit that `#else` that uses `gsettings` is for Linux only and provide a dummy `#else` as well:

```c++
#elif defined(Q_OS_LINUX)
    ...
#else
   return false;
#endif
```

2024-02-24 18:49 UTC, metsma commented on src/controller/application.cpp
>  #else
Why exclude other OS-es where gsettings IS available?

2024-03-01 21:46 UTC, mrts commented on src/controller/application.cpp
>  #else
Are there any OSes like this? I would argue that we should suggest them to use Qt v6.5+. Defaulting to `gsettings` as a general, OS-independent fallback looks fragile to me.

2024-03-04 06:41 UTC, metsma commented on src/controller/application.cpp
>  #else
BSD-s and so on?

2024-03-05 14:26 UTC, mrts commented on src/controller/application.cpp
>  #else
Good point, perhaps we should use `#elif defined(Q_OS_UNIX)` then which is defined on both Linux and BSDs as a defensive measure?

2024-03-12 10:55 UTC, mrts approved these changes

2024-03-12 17:55 UTC, merged