Fixed some TODOs
web-eid/web-eid-app pull request #304
Opened 2023-11-30 12:03 UTC by lauris71

WE2-145

FixedTODOs that do not need major code refactoring

Signed-off-by: Lauris Kaplinski <lauris@raulwalter.com>

2024-05-14 19:11 UTC, mrts requested changes

2024-05-14 19:11 UTC, mrts commented on src/controller/controller.cpp
> +}
We should avoid code duplication. Also, ERR_WEBEID_INVALID_INVOCATION requires a lot of changes in upper layer error handling, is not backwards-compatible and is a minor, very unlikely sub-case of technical errors. Considering this, can we just revert this and leave a generic ERR_WEBEID_NATIVE_FATAL?

2024-05-14 19:11 UTC, mrts commented on src/ui/webeiddialog.cpp
> +        return {tr("Error communicating with the card. Please try again."), tr("Operation failed"),
The translations must be updated as well, see [this section of README](https://github.com/web-eid/web-eid-app?tab=readme-ov-file#adding-and-updating-translations).

2024-05-14 19:11 UTC, mrts commented on src/ui/webeiddialog.cpp
> +        // We use setText instead of clear, so undo/redo will be cleared as well
Perhaps
```suggestion
        // Use setText() instead of clear() to clear undo/redo history as well.
```

2024-05-14 19:11 UTC, mrts commented on src/ui/webeiddialog.cpp
> +        // - DOes not leak content through accessibility interface
Perhaps
```suggestion
        // TODO: Implement a custom widget to ensure no copy of the PIN text remains in memory.
        // The widget should:
        // - store the PIN in a locked byte vector,
        // - prevent content leaks via the accessibility interface.
```

2024-05-15 08:34 UTC, lauris71 reviewed
Tundub väga mõistlik

2024-06-10 07:02 UTC, lauris71 reviewed
ok

2024-06-21 16:19 UTC, mrts approved these changes

2024-06-21 16:26 UTC, merged